version: "3.7"

services:
  backend:
    container_name: backend
    restart: unless-stopped
    build: ./Server
    ports:
      - "3001:3001"
    networks:
      - internal
    depends_on:
      - db

  frontend:
    container_name: frontend
    restart: unless-stopped
    build: ./client
    # environment:
    #   - NODE_PATH=/app/src
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - internal

  db:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: node-app
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - internal

networks:
  internal:

volumes:
  mongo_data: {}
  mongo_config: {}
